name: CI do Projeto GerenciadorPedidos

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executar testes com Maven
        run: mvn test

      - name: Armazenar relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: Relatorios de Teste
          path: target/surefire-reports/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Empacotar o projeto
        run: mvn package

      - name: Armazenar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: Pacote Build
          path: target/*.jar

  notificacao:
    runs-on: ubuntu-latest
    needs: [testes, build]
    if: always()
    steps:
      - name: Instalar software necessário para o pipeline
        run: |
          sudo apt-get install -y mailutils

      - name: Enviar e-mail de notificação
        run: |
          BODY="O pipeline do projeto GerenciadorPedidos foi executado."
          echo "$BODY" | mail -s "Status do Pipeline" ${{ secrets.EMAIL_NOTIFICACAO }}